image: node:6.9.1

services:
  - mongo

stages:
  - build
  - test
  - deploy

before_script:
  # Install ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use a CentOS-based image)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

  # For Docker builds disable host key checking. Be aware that by adding that
  # you are suspectible to man-in-the-middle attacks.
  # WARNING: Use this only with the Docker executor, if you use it with shell
  # you will overwrite your user's SSH config.
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
      paths:
        - node_modules/
        - dist/

test:
  stage: test
  variables:
    CI: "true"
    MONGO_URL: "mongodb://mongo/test-db"
  script:
   - npm run lint
   - npm run testCI

#deploy_staging:
#  stage: deploy
#  script:
#    - cd deploy
#    - ./deployStaging.sh
#  environment:
#    name: staging
#    url:
#  only:
#  - dev
