swagger: "2.0"
info:
  version: 1.0.0
  title: Boilerplate
  description: Boilerplate
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
schemes:
  - http
# will be prefixed to all paths
# basePath: http://nomis.sadek.usermd.net/api
consumes:
  - application/json
produces:
  - application/json

paths: